aris-i/emberflow

src/index.ts, src/sample-custom/security.ts, src/tests/index.test.ts, src/types.ts
Added docPath to be passed in SecurityFn.
=> Added DocPath In Security Fn

src/index-utils.ts, src/index.ts, src/sample-custom/db-structure.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts, src/tests/utils/paths.test.ts, src/types.ts, src/utils/paths.ts
Added unit test.
Replaced srcPath with path in index-utils.ts line 263 to get the actual document data that needs to be copied.
=> Issue#19-Implement-Recursive-Copy-And-Recursive-Delete

src/index-utils.ts, src/tests/index-utils.test.ts, src/tests/utils/distribution.test.ts, src/tests/utils/forms.test.ts, src/tests/utils/misc.test.ts, src/tests/utils/pubsub.test.ts, src/utils/misc.ts
=> Unit-Test-Dec-12

src/index-utils.ts, src/index.ts, src/utils/bill-protect.ts
Converted all v1 functions to v2 functions except onBudgetAlert.
=> Issue#29-Convert-All-Pubsub-to-V2-Functions

src/logics/view-logics.ts, src/sample-custom/db-structure.ts, src/tests/logics/view-logics.test.ts, src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Applied tracking of processed ids to all pubsub.
Re-added db-structure game entity.
=> Issue-28-Apply-Tracking-of-Processed-Ids

src/index.ts, src/tests/utils/forms.test.ts, src/tests/utils/misc.test.ts, src/tests/utils/pubsub.test.ts, src/utils/forms.ts, src/utils/misc.ts, src/utils/pubsub.ts
Added hourly function to delete forms that are 7 days old.
=> Issue-27-Add-Hourly-Cleanup-of-Forms

package-lock.json, src/index-utils.ts, src/index.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts, src/tests/utils/forms.test.ts, src/tests/utils/misc.test.ts, src/tests/utils/pubsub.test.ts, src/types.ts, src/utils/forms.ts, src/utils/misc.ts, src/utils/pubsub.ts
Updated deleteQueryBatch callback to be optional.
=> PR-33-Callback-Update

src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Converts arr+ and arr- with arrayUnion and arrayRemove respectively in onMessageInstructionsQueue.
=> Field-Array-Implementation

package-lock.json, package.json, src/index.ts, src/tests/index.test.ts, src/tests/utils/forms.test.ts, src/utils/forms.ts
Updated admin-client to latest version.
Implemented submitFormAs on submitForm.
Updated tests.
=> Submit-Form-As-Implementation

package-lock.json, src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts, src/tests/logics/view-logics.test.ts, src/types.ts
Implementation of simulate-submit-form and unit tests.
=> simulate-submit-form

src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/sample-custom/db-structure.ts, src/tests/index-utils.test.ts, src/tests/logics/view-logics.test.ts, src/tests/utils/distribution.test.ts, src/tests/utils/forms.test.ts, src/tests/utils/paths.test.ts, src/tests/utils/pubsub.test.ts, src/utils/distribution.ts, src/utils/forms.ts, src/utils/pubsub.ts
Replaced timestamp with timeCreated in cleanActionsAndForms.A
dded createPubSubTopics.
Added status error in runBusinessLogics.
Added callback in cleanPubSubProcessedIds.
=> Fix-Minor-Bugs

src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/sample-custom/db-structure.ts, src/tests/index-utils.test.ts, src/tests/logics/view-logics.test.ts, src/tests/utils/distribution.test.ts, src/tests/utils/forms.test.ts, src/tests/utils/paths.test.ts, src/tests/utils/pubsub.test.ts, src/utils/distribution.ts, src/utils/forms.ts, src/utils/pubsub.ts
For monitoring of logic performance.
=> Business-Logics-Metrics

src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Updated arr instruction implementation.
Added del instruction implementation.
=> Arr-And-Del-Instructions-Implementation

package-lock.json, package.json, src/index-utils.ts, src/index.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts, src/tests/utils/forms.test.ts, src/tests/utils/paths.test.ts, src/tests/utils/pubsub.test.ts, src/utils/forms.ts, src/utils/pubsub.ts
Remove async from init emberflow.
Fixed failing tests.
=> remove-async-from-init-emberflow

src/tests/logics/view-logics.test.ts, src/tests/utils/distribution.test.ts, src/tests/utils/forms.test.ts
Removed createPubSubTopics mocks.
=> remove-createpubsubtopics-mocks

src/index.ts, src/logics/view-logics.ts, src/tests/index.test.ts, src/tests/logics/view-logics.test.ts, src/tests/utils/pubsub.test.ts
Updated docs passed to queueRunViewLogics.
Removed function related to peer sync.
=> Run-View-Logcs-Update-and-Peer-Sync-Removal

src/index.ts, src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Bug fix view logics not running for non high priority docs
=> bug-fix-view-logics-not-running-for-non-high-priority-docs

src/index-utils.ts, src/index.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts
Optimization target docpath is always distributed first.
Updated unit tests.
=> optimization-target-docpath-is-always-distributed-first

src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Fix bug instructions reducer does not trigger view logics.
Updated unit tests.
=> fix-bug-instructions-reducer-does-not-trigger-view-logics

src/index-utils.ts, src/index.ts, src/tests/index-utils.test.ts, src/types.ts
Renamed metric functions.
Added createMetricComputation and cleanMetricComputations.
=> logics-execution-computation

src/index-utils.ts, src/index.ts
=> minor-bug-fix

src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/tests/index-utils.test.ts, src/tests/logics/view-logics.test.ts, src/types.ts
View logic optimization and unit tests.
=> view-logic-optimization

src/index.ts, src/tests/utils/misc.test.ts, src/utils/misc.ts
=> trim-string-inputs

src/index-utils.ts, src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts
Fixed view logic trying to update non-existent view doc.
Added view logic metric.
=> view-logic-bug-fix-and-metric

src/index-utils.ts, src/index.ts, src/init-db-structure.ts, src/logics/view-logics.ts, src/tests/index-utils.test.ts, src/tests/init-db-structure.test.ts, src/tests/logics/view-logics.test.ts, src/types.ts
Fixed view logic being triggered by merge action.
Added vdId to view flags.
=> view-logic-bug-fix

src/logics/view-logics.ts
Added return to buildViewsCollection when action is delete.
No longer updates view flag when action is delete.
=> view-logic-action-delete-bug-fix

src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts, src/types.ts
Added skipRunViewLogics in LogicResultDoc.
Queue run view logic not called when skipRunViewLogics is true.
Replaced view id created with path.
srcToDstLogicFn sets flag to true when action is create.
Added create to srcToDestLogicConfig action types.
Updated unit tests.
=> view-logic-bugs-fix

src/index.ts, src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts
Fixed syncing of @views docs returning an error.
=> viewlogic-error-inline-patch

src/index-utils.ts, src/utils/distribution.ts
Added empty instructions check
=> empty-instructions-bug-fix

src/tests/utils/functions.test.ts, src/utils/functions.ts
=> debounce-bug-fix

src/tests/utils/distribution.test.ts, src/utils/distribution.ts
Added empty check when applying instructions
=> minor-instructions-bug-fix

src/index-utils.ts, src/logics/view-logics.ts, src/tests/index-utils.test.ts, src/tests/logics/view-logics.test.ts, src/utils/distribution.ts
Added console debugs also to understand case where there's a view but viewPathDocs.length is zero
Fixed failing tests
=> fix-bug-when-deleting-src-viewsAlreadyBuilt-flag-is-also-deleted

src/index.ts, src/tests/index.test.ts, src/types.ts, src/utils/distribution.ts
Implementation of transactions.
Updated unit tests.
=> transactions

src/index-utils.ts, src/index.ts, src/tests/index-utils.test.ts, src/types.ts
=> transactions-double-entry

src/index.ts, src/tests/index.test.ts
Added date to ledger and equation.
=> ledger-additional-fields

src/index.ts, src/tests/index.test.ts
Added queueRunViewLogics when writing journal entries.
Skipped logic result docs with journal and action delete.
=> added-queue-run-view-logics-for-journal

src/index-utils.ts, src/tests/index-utils.test.ts, src/types.ts
Added unit test for addtlFilterFn
=> addtlFilterFn-unit-test

src/index-utils.ts, src/index.ts, src/init-db-structure.ts, src/logics/view-logics.ts, src/sample-custom/db-structure.ts, src/tests/index-utils.test.ts, src/tests/init-db-structure.test.ts, src/tests/logics/view-logics.test.ts, src/types.ts, src/utils/paths.ts
Implementation of array view logic.
=> array-view-logic

src/index-utils.ts, src/tests/index-utils.test.ts, src/tests/utils/batch.test.ts, src/utils/batch.ts
Replaced update with set so that logic result docs with merge action will create docs if not yet existing.
=> Distribute-Doc-Update

src/index.ts, src/logics/view-logics.ts, src/utils/distribution.ts, src/utils/forms.ts
Updated console logs and added console debugs to track logic result docs.
=> Logic-Results-Bug-Tracking

src/index.ts, src/tests/index.test.ts
Added execTime to action and Also added metrics for validating Form, Security, Delay, Business Logics and onFormSubmit
=> Added execTime to action and Also added metrics for validating Form, Security, Delay, Business Logics and onFormSubmit

package-lock.json, package.json
Upgraded emberflow admin client
=> Emberflow-Client-Upgrade

src/index-utils.ts, src/index.ts
1. Used distributeDoc in transactional 
2. Update distributeDoc to use transactional for update/delete/set and processing of instructions
=> Updated distributeDoc to accommodate transaction

src/index-utils.ts, src/logics/view-logics.ts, src/sample-custom/db-structure.ts, src/tests/index.test.ts, src/tests/logics/view-logics.test.ts
1. @aris-i Created the formSrcPath() in view logics
2. I added test cases for the formSrcPath
=> Non global collection src view

src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts
Fixed: field update with 0 values is being removed and is not being synced by view logics
=> FIX: Views not syncing 0 values

src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts, src/utils/paths.ts
1. Added condition for checking if the document exists in syncMerge, if not delete the viewDoc 
2. Return basePath in getDestPropAndPropId util function.
3. Fixed tests
=> Cleanup stale views document

src/logics/view-logics.ts, src/tests/logics/view-logics.test.ts
Updated createViewLogicFn to prioritize doc values when forming source path
=> FIX: Prioritize doc values when forming source path

src/index-utils.ts, src/index.ts, src/logics/view-logics.ts, src/tests/index-utils.test.ts, src/tests/index.test.ts, src/tests/logics/view-logics.test.ts, src/types.ts, src/utils/distribution.ts, src/utils/paths.ts
@aris-i Please do not merge yet.
=> Queue run view logics should run after transaction

src/tests/utils/distribution.test.ts, src/utils/distribution.ts
use parseFloat in converting instructions to db values
=> FIX: using parseFloat in instructions

package-lock.json, package.json, src/index.ts, src/utils/misc.ts
devDependencies
firebase-functions-test =>^3.4.1
dependencies:
emberflow-admin-client => 1.2.6
peerDependencies
firebase-admin => ^13.4.0
firebase-functions =>^6.3.2
=> Upgrade firebase-functions and firebase-admin

src/index.ts
Stringify the validation error message
=> Stringify the validation error message

package-lock.json, package.json, src/index.ts, src/tests/utils/forms.test.ts, src/utils/forms.ts
Upgraded emberflow-admin-client to version 1.2.7
=> emberflow-admin-client

src/index-utils.ts, src/tests/utils/forms.test.ts, src/utils/forms.ts
Add @docpath in submit-form doc to accomodate logicResultDocs from BE
=> Add @docpath in submit-form doc
